baseURL = 'https://0reab.github.io/'
languageCode = 'en-us'
title = "Reab"
theme = "enervoid"

[menus]
  [[menus.main]]
    name = 'About me'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10

  [[menus.main]]
    name = 'Personal'
    pageRef = '/personal'
    weight = 20

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30

[params]
  avatar = "https://avatars.githubusercontent.com/u/122540000?v=4"
  customCSS = ["css/custom.css"]

  [[params.socials]]
      link = "https://github.com/0Reab"
      icon = "devicon-github-original"
  [[params.socials]]
      link = "https://www.linkedin.com/in/mihajlo-francic-3650682bb"
      icon = "devicon-linkedin-plain"
  [[params.socials]]
      link = "https://www.instagram.com/astrosamihajlom/"
      icon = "si-instagram"
      color = "dbdbdb"
  [[params.socials]]
      #name = "OpenBugBounty"
      link = "https://app.intigriti.com/researcher/profile/reab"
      icon = "si-intigriti"
      color = "ffffff"
  [[params.socials]]
      link = "https://www.openbugbounty.org/researchers/reab/"
      icon = "si-openbugbounty"
      color = "dbdbdb"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$','$$'], ['\\[','\\]']]
        inline = [['$','$'], ['\\(','\\)']]

    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[markup.highlight]
  noClasses = true
  codeFences = true
  guessSyntax = true
  tabWidth = 4
  style = "monokai"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
